apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      #- MINIKUBE_IP/24
      - 192.168.99.95-192.168.99.105
