apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
      - name: mysql
        image: alpine:3.12
        imagePullPolicy: Never
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: PMA_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: PMA_USER
        - name: PMA_PASSWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: PMA_PASSWD
        - name: WP_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: WP_USER
        - name: WP_PASSWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: WP_PASSWD
        command: ["/bin/sh"]
        args: ["-c", "sleep 6000"]
        volumeMounts:
        - name: mysql-persistent-volume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-volume
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-app
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  PMA_USER: eWVraW0=
  PMA_PASSWD: NTkzMw==
  WP_USER: d29yZHByZXNz
  WP_PASSWD: cGFzc3dk 
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    run: mysql
spec:
  ports:
  - port: 3306
    protocol: TCP
    name: mysql
  selector:
    app: mysql
