apiVersion: 1
datasources:
- name: influxdb
  orgId: 1
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  database: telegraf
  user: yekim
  password: 5933
  isDefault: false
  version: 1
  editable: false
