apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: yekim_phpmyadmin:1.0
        imagePullPolicy: Never
        env:
        - name: PMA_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: PMA_USER
        - name: PMA_PASSWD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: PMA_PASSWD
        command: ["/bin/sh"]
        args: ["-c", "sleep 6000"]
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  labels:
    run: phpmyadmin
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
  - port: 5000
    protocol: TCP
    name: http
