apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: yekim_nginx:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        env:
        - name: SSH_USER
          valueFrom:
            secretKeyRef:
              name: nginx-ssh-user
              key: SSH_USER
        - name: SSH_PASSWD
          valueFrom:
            secretKeyRef:
              name: nginx-ssh-user
              key: SSH_PASSWD
        volumeMounts:
        - name: nginx-secret
          mountPath: /etc/ssl
        - name: nginx-config
          mountPath: /etc/nginx/
        command: ["/bin/sh"]
        args: ["-c", "sleep 3"]
      volumes:
      - name: nginx-secret
        secret:
          secretName: nginx-secret
      - name: nginx-config
        configMap:
          name: nginx-config

