apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    run: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
  - port: 22
    protocol: TCP
    name: ssh
