apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    run: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - port: 20
    protocol: TCP
    name: ftps-data
  - port: 21
    protocol: TCP
    name: ftps
  - port: 21100
    protocol: TCP
    name: passive0
  - port: 21101
    protocol: TCP
    name: passive1
